@authAdmin = YWRtaW46YWRtaW4
@authUser = dXNlcjp1c2Vy
GET http://localhost:8080/boats/read/1
Authorization: Basic {{authUser}}

###

GET http://localhost:8080/boats/read/all
Authorization: Basic {{authUser}}
###

PUT http://localhost:8080/boats/update/ HTTP/1.1
Authorization: Basic {{authUser}}
content-type: application/json

{
    "id": "1",
    "name": "first update",
    "description": "first updated boat" 
}

###

POST http://localhost:8080/boats/create/ HTTP/1.1
Authorization: Basic {{authUser}}
content-type: application/json

{
    "id": null,
    "name": "added",
    "description": "added boat" 
}

###

POST http://localhost:8080/users/create/ HTTP/1.1
Authorization: Basic {{authAdmin}}
Content-Type: application/json

{
    "id": null,
    "username": "otherUser",
    "password": "user",
    "roles": [
        {"name": "ROLE_USER"}
    ]
}

###

GET http://localhost:8080/users/read/1
Authorization: Basic {{authAdmin}}

###
GET http://localhost:8080/authenticate
Authorization: Basic {{authUser}}