name: Publish Docker Image

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: boats-jar

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/boats-backend:latest ./back

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/boats-backend:latest